# Generated by Django 3.1.3 on 2020-12-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue')], max_length=256),
        ),
    ]
