# Generated by Django 3.1.3 on 2020-12-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec_api', '0002_auto_20201225_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
