host = 'http://127.0.0.1:8000/api/'
post_data = {}
post_data['store_passwd'] = "local5fe5dbe84be11@ssl"
post_data["store_id"] = "local5fe5dbe84be11"
# post_data['total_amount'] = total
# post_data['amount'] = "50"
post_data['currency'] = "BDT"
# post_data['tran_id'] = tran_id
post_data['shipping_method'] = 'YES'
post_data['product_name'] = 'CLOTHE'
post_data['product_profile'] = 'Cloth'
post_data['product_category'] = "CLothing"
post_data['success_url'] = host+"sslcommerz/success/"
post_data['fail_url'] = host + "sslcommerz/fail/"
post_data['cancel_url'] = host + "sslcommerz/cancel/"
post_data['ship_name'] = "testlocalite7"
post_data['ship_add1'] = "Dhaka"
post_data['ship_add2'] = "Dhaka"
post_data['ship_city'] = "Dhaka"
post_data['ship_state'] = "Dhaka"
post_data['ship_postcode'] = "1000"
post_data['ship_country'] = "Bangladesh"
post_data['emi_option'] = "0"
post_data['product_amount'] = "100"
post_data['vat'] = "5"
post_data['discount_amount'] = "5"
post_data['convenience_fee'] = "3"
post_data['cus_name'] = "Roton"
post_data['cus_email'] = "wsakib88@gmail.com"
post_data['cus_add1'] = "Dhaka"
post_data['cus_add2'] = "Dhaka"
post_data['cus_city'] = "Dhaka"
post_data['cus_state'] = "Dhaka"
post_data['cus_postcode'] = "1000"
post_data['cus_country'] = "Bangladesh"
post_data['cus_phone'] = '+8801854582598'
post_data['cus_fax'] = ""
post_data['cart'] = []